#src/main/resources/application.yaml

server:
  port: 8888

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ItRProjectDB
    username: root
    password: rootpass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  h2:
    console:
      enabled: false