#src/main/resources/application.yaml

server:
  port: 8888

spring:
  datasource:
    # url: jdbc:mariadb://localhost:3306/${MYSQL_DATABASE}
    # username: ${MYSQL_USER}
    # password: ${MYSQL_PASSWORD}

    # To get env vars you need to provide them another way. IF not provided
    # Through docker you are cooked
    driver-class-name: org.mariadb.jdbc.Driver

  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true

  # h2:
  #   console:
  #     enabled: false